### ISSUE TITLE
Unable to run HEFTPolicy.java

### ISSUE THREAD

**Issue by niranjan92** [pedropaulovc/CloudSim_DVFS#1]
hi! I am new to cloudsim. Need to run an example for HEFT Policy. I tried modifying Dvfs_example_simple.java where I tried replacing PowerVmAllocationPolicySimpleWattPerMipsMetric with HEFTPolicy. But it didn't work giving following error: 

The constructor PowerDatacenter(String, DatacenterCharacteristics, HEFTPolicy, LinkedList<Storage>, double) is undefined

On further analysis, I found that HEFTPolicy extends Policy while PowerVmAllocationPolicySimpleWattPerMipsMetric extends VmAllocationPolicy. 

Is there any code example by which I can get the HEFTPolicy running?

**Comment by pedropaulovc** [comment]
Hey Niranjan,

I'm sorry but it's been almost three years since I worked on this project. It would take me a long time to remember all details before I can answer your question.

Good luck with your research,
Pedro Paulo
